export const imgData = [
  [
    "/src/assets/work/phone1.jpg",
    "/src/assets/work/phone2.jpg",
    "/src/assets/work/phone3.jpg",
  ],
  [
    "/src/assets/work/web2.jpg",
    "/src/assets/work/web3.jpg",
    "/src/assets/work/web4.jpg",
    "/src/assets/work/web5.jpg",
    "/src/assets/work/web6.jpg",
  ],
  [
    "/src/assets/work/web6.jpg",
    "/src/assets/work/phone1.jpg",
    "/src/assets/work/phone2.jpg",
    "/src/assets/work/phone3.jpg",
    "/src/assets/work/web2.jpg",
    "/src/assets/work/web3.jpg",
    "/src/assets/work/web4.jpg",
    "/src/assets/work/web5.jpg",
  ],
];
